#!/usr/bin/env node
// CLI entry point: `npm run data-report`.
// Regenerates docs/dev/KNOWLEDGE-QA.md from the current repository state.
// Answers "what does the dataset currently look like?" — a snapshot, not
// a pass/fail check (that's scripts/validate-data.js).
//
// Implements Task H / Task K of
// docs/architecture/PHASE-2-SCHEMA-AND-DATA-GOVERNANCE.md.

const fs = require('fs');
const path = require('path');
const { loadAllRecords } = require('./lib/load-records');
const { validate } = require('./lib/validate');
const { OPTIONAL_LIST_FIELDS } = require('./lib/taxonomy');

const OUTPUT_PATH = path.join(__dirname, '..', 'docs', 'dev', 'KNOWLEDGE-QA.md');

// Claim-language heuristic reused from the manual evidence-notes audits
// this project ran by hand earlier — kept here as an automated proxy,
// not a substitute for the judgment those audits used. False positives
// are expected and should be checked by hand, same as before.
const CLAIM_TERMS = [
  'commonly cited', 'commonly associated', 'strongest available', 'most responsible',
  'most demanding', 'most effective', 'primary driver', 'stretch-mediated', 'biased',
];

function hasClaimLanguage(record) {
  const blob = [
    record.summary, record.why_this_exists,
    JSON.stringify(record.primary_targets || []),
    JSON.stringify(record.best_used_when || []),
    JSON.stringify(record.less_suitable_when || []),
  ].join(' ').toLowerCase();
  return CLAIM_TERMS.some((t) => blob.includes(t));
}

function main() {
  const { records, fileErrors, files } = loadAllRecords();
  const { issues, duplicateIds } = validate(records);

  const byStatus = { draft: 0, 'needs-review': 0, reviewed: 0 };
  for (const r of records) {
    if (byStatus[r.review_status] !== undefined) byStatus[r.review_status] += 1;
  }

  const schemaViolations = issues.filter((i) => i.category === 'schema');
  const taxonomyViolations = issues.filter((i) => i.category === 'taxonomy');
  const relationshipViolations = issues.filter((i) => i.category === 'relationship');
  const governanceViolations = issues.filter((i) => i.category === 'governance');

  // Duplicate canonical exercises: same display name, different ids.
  const byName = new Map();
  for (const r of records) {
    if (!byName.has(r.name)) byName.set(r.name, new Set());
    byName.get(r.name).add(r.id);
  }
  const duplicateNames = [...byName.entries()].filter(([, ids]) => ids.size > 1);

  const crossModule = records.filter((r) => (r.body_regions || []).length > 1);

  const missingMirrorEffect = records.filter((r) => !(r.mirror_effect || '').trim());
  const missingEvidenceWhereClaimed = records.filter(
    (r) => hasClaimLanguage(r) && !(r.evidence_notes || []).length
  );

  // "Incomplete applicable fields" — per-optional-field count of records
  // still at true emptiness ([] / ""), which per ADR 0002 means "not yet
  // established" rather than "not applicable" (null would mean that).
  const incompleteByField = OPTIONAL_LIST_FIELDS.map((field) => {
    const emptyCount = records.filter((r) => {
      const v = r[field];
      return v === null || v === undefined ? false : Array.isArray(v) && v.length === 0;
    }).length;
    const nullCount = records.filter((r) => r[field] === null).length;
    return { field, emptyCount, nullCount };
  }).filter((f) => f.emptyCount > 0);

  const lines = [];
  const add = (s = '') => lines.push(s);

  add('# Knowledge QA Report');
  add();
  add('**Generated by:** `npm run data-report` (`scripts/data-report.js`) — regenerate after any dataset change rather than editing this file by hand.');
  add(`**Generated at:** ${new Date().toISOString()}`);
  add();
  add('This report answers "what does the dataset currently look like?" `npm run validate-data` answers "is it valid?" — keep the two separate per Task K of the [Phase 2 spec](../architecture/PHASE-2-SCHEMA-AND-DATA-GOVERNANCE.md).');
  add();
  add('## Totals');
  add();
  add(`- Total canonical exercises: **${records.length}**`);
  add(`- Reviewed: **${byStatus.reviewed}**`);
  add(`- Needs-review: **${byStatus['needs-review']}**`);
  add(`- Draft: **${byStatus.draft}**`);
  add();
  add('## Validation summary');
  add();
  add(`- Schema violations: **${schemaViolations.length}**`);
  add(`- Taxonomy violations: **${taxonomyViolations.length}**`);
  add(`- Invalid relationships: **${relationshipViolations.length}**`);
  add(`- Review-governance violations: **${governanceViolations.length}**`);
  add(`- Duplicate IDs: **${duplicateIds.length}**${duplicateIds.length ? ' — ' + duplicateIds.map((d) => d.id).join(', ') : ''}`);
  add(`- Duplicate canonical exercises (same name, different ids): **${duplicateNames.length}**${duplicateNames.length ? ' — ' + duplicateNames.map(([n]) => n).join(', ') : ''}`);
  add(`- File-level load errors: **${fileErrors.length}**${fileErrors.length ? '\n  - ' + fileErrors.join('\n  - ') : ''}`);
  add();
  add('Full violation detail: run `npm run validate-data`. This report only summarizes counts.');
  add();
  add('## Cross-module exercises');
  add();
  add(`**${crossModule.length}** record(s) declare more than one `+'`body_regions`'+` value (the ADR 0001 dedup pattern):`);
  add();
  if (crossModule.length) {
    for (const r of crossModule) add(`- \`${r.id}\` (${r._file}) — ${r.body_regions.join(', ')}`);
  } else {
    add('- none');
  }
  add();
  add('## Content completeness (optional fields)');
  add();
  add('Per [ADR 0002](../adr/0002-empty-field-semantics.md), an optional field left as a true empty list means "not yet established," not "not applicable" (that\'s what `null` means). Counts below are records where the field is still empty — this is the honest, current content backlog, not a defect.');
  add();
  add('| Field | Empty (not yet established) | Marked `null` (not applicable) |');
  add('|---|---|---|');
  for (const { field, emptyCount, nullCount } of incompleteByField) {
    add(`| \`${field}\` | ${emptyCount}/${records.length} | ${nullCount}/${records.length} |`);
  }
  add();
  add('## Evidence and mirror-effect coverage');
  add();
  add(`- Exercises missing `+'`mirror_effect`'+`: **${missingMirrorEffect.length}**${missingMirrorEffect.length ? ' — ' + missingMirrorEffect.map((r) => r.id).join(', ') : ''}`);
  add(`- Exercises with claim-like language but no `+'`evidence_notes`'+` (heuristic, verify by hand): **${missingEvidenceWhereClaimed.length}**${missingEvidenceWhereClaimed.length ? ' — ' + missingEvidenceWhereClaimed.map((r) => r.id).join(', ') : ''}`);
  add();
  add('## Known, logged exceptions (not bugs — see the linked reasoning)');
  add();
  add('- **`advantages` is empty on all 123 records.** Flagged and awaiting a scoping decision — see [`docs/dev/reports/REVIEW-PROMOTION-GATE.md`](reports/REVIEW-PROMOTION-GATE.md).');
  add('- **`alternatives` is empty on all 123 records.** Flagged in [`SCHEMA.md`](../knowledge-manual/SCHEMA.md#alternatives) — likely redundant with `complements` as currently used, not yet decided.');
  add();

  fs.writeFileSync(OUTPUT_PATH, lines.join('\n') + '\n');
  console.log(`Wrote ${path.relative(process.cwd(), OUTPUT_PATH)} (${records.length} records analyzed).`);
}

main();
